/**
 * head태그 내의 내용이나 상단바를 넣어서 활용. page.js를 감싸는 layout.js
 */
import './globals.css';
import Link from "next/link";

export const metadata = {
  title: 'Next Fresh',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/cart">Cart</Link>
          <Link href="/abc">abc</Link>
        </div>
        {children}
      </body>
    </html>
  );
}